services:
  ha-discovery-service:
    image: rtozer/ha-discovery-service:latest
    environment:
      MQTT_BROKER_HOST: localhost
      MQTT_BROKER_PORT: 1883
      MQTT_USERNAME: ""
      MQTT_PASSWORD: ""
      HA_DISCOVERY_PREFIX: homeassistant
      CHIRPSTACK_UPLINK_TOPIC: application/+/device/+/event/up
      CHIRPSTACK_DOWNLINK_TOPIC: application/+/device/+/command/down
      LOG_LEVEL: INFO
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_config: 