name: Release on Version Change

on:
  push:
    paths:
      - 'VERSION'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extract version
        id: get_version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION | head -n1 | tr -d '\n')
          else
            echo "VERSION file not found!" && exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create zip artifact
        run: |
          zip -r chirpstack_ha-${{ steps.get_version.outputs.version }}.zip custom_components/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release for version ${{ steps.get_version.outputs.version }}.
          files: chirpstack_ha-${{ steps.get_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 